categories = {
    'Winery/Vineyard' : 'WineryVineyard', 
    'Corporate Office' : 'Office',
    'Teacher' : 'Teacher', 
    'Band' : 'Music',
    'Jewelry/Watches' : 'JewelryWatches',
    'Religious Organization' : 'Religion',
    'Festival' : 'Festival',
    'Travel Company' : 'Travel',
    'Political Ideology' : 'Politics',
    'Legal Company' : 'Company',
    'News/Media Website' : 'Website',
    'Agriculture Company' : 'Company',
    'Computer Training School' : 'Computer',
    'Professional Sports Team' : 'Sports',
    'Website' : 'Website',
    'Computers/Internet Website' : 'Website',
    'Police Station' : 'Police',
    'Religious Place of Worship' : 'Religion',
    'Movie/Television Studio' : 'MovieTelevision',
    'Album' : 'Music',
    'Courthouse' : 'Law',
    'Department Store' : 'Store',
    'Restaurant' : 'Food',
    'Shopping & Retail' : 'ShoppingRetail',
    'Record Label' : 'RecordLabel',
    'Society/Culture Website' : 'Website',
    'Arts & Entertainment' : 'ArtsEntertainment',
    'Comedian' : 'Comedian',
    'Non-Profit Organization' : 'Non-ProfitOrganization',
    'Lounge' : 'Lounge',
    'Barber Shop' : 'BarberShop',
    'Personal Blog' : 'Blog',
    'Video Game' : 'Game',
    'Hostel' : 'Hostel',
    'Food & Beverage Company' : 'Company',
    'Technology Company' : 'Company',
    'Artist' : 'Artist', 
    'Government Organization' : 'GovernmentOrganization',
    'Massage Service' : 'Services',
    'Software Company' : 'Company',
    'Scientist' : 'Scientist',
    'Electronics' : 'Electronics',
    'Automotive Company' : 'Company',
    'Recruiter' : 'Recruiter',
    'Stadium, Arena & Sports Venue' : 'Sports',
    'Campus Building' : 'CampusBuilding',
    'Broadcasting & Media Production Company' : 'Company',
    'Consulting Agency' : 'ConsultingAgency',
    'Public & Government Services' : 'Services',
    'City' : 'City',
    'Recreation Center' : 'RecreationCenter',
    'Lawyer' : 'Law',
    'Computers (Brand)' : 'Brand',
    'Region' : 'Region',
    'Just For Fun' : 'JustForFun',
    'Art' : 'Art',
    'Product/Service' : 'ProductService',
    'Shopping District' : 'ShoppingDistrict',
    'Dating Service' : 'Services',
    'Books & Magazines' : 'BooksMagazines',
    'E-commerce Website' : 'E-commerce',
    'Business Consultant' : 'BusinessConsultant',
    'Airport' : 'Airport',
    'Beauty, Cosmetic & Personal Care' : 'BeautyCosmeticPersonalCare',
    'Cause' : 'Cause',
    'Geographical Place' : 'GeographicalPlace',
    'Outdoor, Recreation & Fitness' : 'OutdoorRecreationFitness',
    'Baseball Stadium' : 'Sports',
    'Photographer' : 'Photographer',
    'Music' : 'Music',
    'Music Video' : 'Music', 
    'Phone/Tablet' : 'PhoneTablet',
    'Pub' : 'Pub',
    'Camera/Photo' : 'CameraPhoto',
    'Monarch' : 'Monarch',
    'Library' : 'Library',
    'Sport' : 'Sports',
    'News Personality' : 'NewsPersonality',
    'Education' : 'Education',
    'Organization' : 'Organization',
    'Internet Company' : 'Company',
    'Social Club' : 'SocialClub',
    'School Sports Team' : 'Sports',
    'Advertising/Marketing' : 'AdvertisingMarketing',
    'Locality' : 'Locality',
    'Chef' : 'Chef',
    'Education Company' : 'Company',
    'Industrial Company' : 'Company',
    'Blogger' : 'Blogger',
    'Author' : 'Author',
    'Musician' : 'Musician',
    'Private School' : 'School',
    'Hair Salon' : 'HairSalon',
    'Book Store' : 'Store',
    'DJ' : 'DJ',
    'Newspaper' : 'Newspaper',
    'Coach' : 'Coach',
    'Merchandising Service' : 'Services',
    'Building Materials' : 'BuildingMaterials',
    'Trade School' : 'School',
    'State' : 'State',
    'Media' : 'Media',
    'Health/Beauty' : 'Health/Beauty',
    'Sports League' : 'Sports',
    'Amateur Sports Team' : 'Sports',
    'Concert Tour' : 'ConcertTour',
    'Book' : 'Book',
    'Real Estate' : 'RealEstate',
    'Dancer' : 'Dancer',
    'Reference Website' : 'Website',
    'Casino & Gaming' : 'CasinoGaming',
    'Magazine' : 'Magazine',
    'Workplace & Office' : 'WorkplaceOffice',
    'Automation Service' : 'Services',
    'Non-Governmental Organization (NGO)' : 'NonGovernmentalOrganization',
    'TV' : 'TV',
    'Information Technology Company' : 'Company',
    'Construction Company' : 'Company',
    'Archery Range' : 'ArcheryRange',
    'Entertainment Website' : 'Entertainment',
    'Community' : 'Community',
    'Interest' : 'Interest',
    'Politician' : 'Politician',
    'Political Organization' : 'Politics',
    'Professional Service' : 'Services',
    'Games/Toys' : 'GamesToys',
    'Motorcycle Dealership' : 'Dealership',
    'Presbyterian Church' : 'Church',
    'Public Figure' : 'PublicFigure',
    'Employment Agency' : 'EmploymentAgency',
    'Business Service' : 'Services',
    'Italian Restaurant' : 'Food',
    'Media/News Company' : 'Company',
    'Finance Company' : 'Company',
    'Christian Church' : 'Church',
    'Automotive, Aircraft, Boat' : 'AutomotiveAircraftBoat',
    'Residence' : 'Residence',
    'Internet Service Provider' : 'ISP',
    'Other' : 'Other',
    'Apparel & Clothing' : 'ApparelClothing',
    'Public School' : 'School',
    'Journalist' : 'Journalist',
    'Grocery Store' : 'Store',
    'Public Service' : 'Services',
    'Arts/Humanities Website' : 'Website',
    'Evangelical Church' : 'Church',
    'Movie' : 'Movie',
    'Athlete' : 'Athlete',
    'Performance & Event Venue' : 'PerformanceEventVenue',
    'TV Network' : 'TV',
    'College & University' : 'CollegeUniversity',
    'Wine/Spirits' : 'WineSpirits',
    'TV Show' : 'TVShow',
    'Building Material Store' : 'Store',
    'Martial Arts School' : 'MartialArts',
    'Entrepreneur' : 'Entrepreneur',
    'Energy Company' : 'Company',
    'Medical & Health' : 'MedicalHealth',
    'Producer' : 'Producer',
    'City Hall' : 'CityHall',
    'Fashion Designer' : 'FashionDesigner',
    'Apartment & Condo Building' : 'ApartmentCondoBuilding',
    'Computer Repair Service' : 'Services',
    'Home Decor' : 'HomeDecor',
    'Kitchen/Cooking' : 'KitchenCooking',
    'Personal Website' : 'Website',
    'Gym/Physical Fitness Center' : 'GymPhysicalFitnessCenter',
    'Computer Company' : 'Company',
    'Church' : 'Church',
    'App Page' : 'AppPage',
    'Armed Forces' : 'Military',
    'Plastic Surgeon' : 'PlasticSurgeon',
    'Clothing (Brand)' : 'Brand',
    'Medical Company' : 'Company',
    'Government Official' : 'GovernmentOfficial',
    'Government Building' : 'GovernmentBuilding',
    'Law Enforcement Agency' : 'Law',
    'Company' : 'Company',
    'Pet' : 'Pet',
    'Cosmetics Store' : 'Store',
    'Baptist Church' : 'Church',
    'Science Website' : 'Website',
    'Health Food Store' : 'Store', 
    'TypeAhead' : 'TypeAhead',
    'Advertising Agency' : 'AdvertisingAgency',
    'Cars' : 'Cars',
    'Travel Agency' : 'TravelAgency',
    'Business Center' : 'BusinessCenter',
    'Religious Center' : 'Religion',
    'Local/Travel Website' : 'Website',
    'Tools/Equipment' : 'ToolsEquipment',
    'Regional Website' : 'Website',
    'Fictional Character' : 'FictionalCharacter',
    'Bar' : 'Bar',
    'Local Service' : 'Services',
    'Food & Beverage' : 'FoodBeverage', 
    'Telecommunication Company' : 'Company',
    'Profile' : 'Profile',
    'Gastropub' : 'Gastropub',
    'Performance Art Theatre' : 'PerformanceArtTheatre',
    'Local Business' : 'LocalBusiness',
    'Military Base' : 'Military',
    'Specialty School' : 'School',
    'Event' : 'Event',
    'Beach' : 'Beach',
    'TV Channel' : 'TV',
    'Song' : 'Music',
    'Electronics Store' : 'Store',
    'Education Website' : 'Website',
    'Brand' : 'Brand',
    'Shopping Mall' : 'ShoppingMall',
    'Language School' : 'School',
    'Event Planner' : 'EventPlanner',
    'Community Organization' : 'CommunityOrganization', 
    'Sports Team' : 'Sports',
    'Recreation/Sports Website' : 'Website',
    'Home' : 'Home',
    'Movie Theater' : 'MovieTheater',
    'Writer' : 'Writer',
    'Hotel' : 'Hotel',
    'Business/Economy Website' : 'Website',
    'Pharmaceuticals' : 'Pharmaceuticals',
    'Retail Company' : 'Company',
    'Sports Club' : 'Sports',
    'Music Chart' : 'Music',
    'Political Party' : 'Politics',
    'Burger Restaurant' : 'Food',
    'Radio Station' : 'Radio',
    'Publisher' : 'Publisher',
    'Community Services' : 'Services',
    'High School' : 'School', 
    'Fashion' : 'Fashion',
    'Musician/Band' : 'Music',
    'Biotechnology Company' : 'Company',
    'Book & Magazine Distributor' : 'BookMagazine',
    'School' : 'School',
    'Software' : 'Computer'
}